// Command hudfont extracts Doom's status-bar digit glyphs (STTNUM0-9)
// from a WAD and writes them into aiplay/perception as Go source.
//
// This is a maintainer tool, run once and its output committed -- same
// arrangement as tools/vendorimages. It exists because aiplay reads the
// on-screen HUD to tell System 1 the player's health, ammo and armor,
// and matching a digit on screen needs to know what each digit looks
// like. The WAD is the authoritative source for that, but it ships in
// the game image, not aiplay's, so the glyphs are baked into aiplay at
// build time instead of parsed at runtime.
//
//	go run ./tools/hudfont            # rewrites the generated file
//	go run ./tools/hudfont -check     # fails if it would change (CI)
package main

import (
	"bytes"
	"encoding/binary"
	"flag"
	"fmt"
	"os"
	"strings"

	"zcxdoom/tools/internal/repopath"
)

// Doom's status bar draws its digits from the red end of the palette.
// Indices 176-191 are that ramp, brightest first; the rest of a digit
// patch is the dark outline and, for glyphs like 0 and 8, the enclosed
// hole. Splitting the ramp here separates "lit body of the stroke" from
// outline and hole, which is what actually distinguishes one digit from
// another -- the patches are otherwise solid rectangles of pixels (every
// column is one unbroken post), so a plain "is there a pixel here" mask
// makes 0, 8 and 6 identical.
const (
	bodyFirst = 176
	bodyLast  = 186
)

type lump struct {
	pos, size uint32
	name      string
}

func main() {
	check := flag.Bool("check", false, "exit non-zero if the generated file is out of date instead of rewriting it")
	wadPath := flag.String("wad", "", "path to the WAD (default: assets/doom1.wad in this repo)")
	outPath := flag.String("out", "", "path to write (default: aiplay/perception/hudfont.go in this repo)")
	flag.Parse()

	root, err := repopath.Root()
	if err != nil {
		fatal(err)
	}
	if *wadPath == "" {
		*wadPath = root + "/assets/doom1.wad"
	}
	if *outPath == "" {
		*outPath = root + "/aiplay/perception/hudfont.go"
	}

	data, err := os.ReadFile(*wadPath)
	if err != nil {
		fatal(err)
	}
	lumps, err := directory(data)
	if err != nil {
		fatal(err)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// Code generated by tools/hudfont from assets/doom1.wad. DO NOT EDIT.

package perception

// digitGlyphs[n] is Doom's status-bar glyph for the digit n: '#' where
// the lit body of the stroke is, '.' for outline, hole, or nothing. See
// tools/hudfont for how these are derived and why the body matters
// rather than the full pixel mask.
var digitGlyphs = [10][]string{
`)
	for n := 0; n < 10; n++ {
		name := fmt.Sprintf("STTNUM%d", n)
		l, ok := find(lumps, name)
		if !ok {
			fatal(fmt.Errorf("%s not found in %s", name, *wadPath))
		}
		w, h, rows := glyph(data[l.pos : l.pos+l.size])
		if w != GlyphW || h != GlyphH {
			fatal(fmt.Errorf("%s is %dx%d, expected %dx%d -- perception's HUD geometry assumes the latter", name, w, h, GlyphW, GlyphH))
		}
		fmt.Fprintf(&buf, "\t%d: {\n", n)
		for _, r := range rows {
			fmt.Fprintf(&buf, "\t\t%q,\n", r)
		}
		fmt.Fprintf(&buf, "\t},\n")
	}
	fmt.Fprintf(&buf, "}\n")

	if *check {
		old, err := os.ReadFile(*outPath)
		if err != nil {
			fatal(err)
		}
		if !bytes.Equal(old, buf.Bytes()) {
			fmt.Fprintf(os.Stderr, "%s is out of date; run: go run ./tools/hudfont\n", *outPath)
			os.Exit(1)
		}
		fmt.Printf("%s is up to date\n", *outPath)
		return
	}
	if err := os.WriteFile(*outPath, buf.Bytes(), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("wrote %s (10 glyphs from %s)\n", *outPath, *wadPath)
}

// GlyphW/GlyphH are what every STTNUM patch measures, and what
// perception's cell geometry is built on. Checked, not assumed.
const (
	GlyphW = 13
	GlyphH = 16
)

func directory(data []byte) ([]lump, error) {
	if len(data) < 12 {
		return nil, fmt.Errorf("too short to be a WAD")
	}
	if id := string(data[0:4]); id != "IWAD" && id != "PWAD" {
		return nil, fmt.Errorf("not a WAD (magic %q)", id)
	}
	num := binary.LittleEndian.Uint32(data[4:8])
	off := binary.LittleEndian.Uint32(data[8:12])
	var lumps []lump
	for i := uint32(0); i < num; i++ {
		e := data[off+i*16:]
		lumps = append(lumps, lump{
			pos:  binary.LittleEndian.Uint32(e[0:4]),
			size: binary.LittleEndian.Uint32(e[4:8]),
			name: strings.TrimRight(string(e[8:16]), "\x00"),
		})
	}
	return lumps, nil
}

func find(lumps []lump, name string) (lump, bool) {
	for _, l := range lumps {
		if l.name == name {
			return l, true
		}
	}
	return lump{}, false
}

// glyph decodes one Doom picture-format lump into rows of '#'/'.',
// marking only palette indices in the lit-body range.
func glyph(b []byte) (w, h int, rows []string) {
	w = int(int16(binary.LittleEndian.Uint16(b[0:2])))
	h = int(int16(binary.LittleEndian.Uint16(b[2:4])))
	grid := make([][]byte, h)
	for i := range grid {
		grid[i] = bytes.Repeat([]byte("."), w)
	}
	for col := 0; col < w; col++ {
		p := int(binary.LittleEndian.Uint32(b[8+col*4 : 12+col*4]))
		for {
			top := b[p]
			if top == 0xFF {
				break
			}
			n := int(b[p+1])
			// Post layout: topdelta, length, pad, length pixels, pad.
			for i := 0; i < n; i++ {
				y := int(top) + i
				if idx := b[p+3+i]; y >= 0 && y < h && idx >= bodyFirst && idx <= bodyLast {
					grid[y][col] = '#'
				}
			}
			p += 3 + n + 1
		}
	}
	for _, r := range grid {
		rows = append(rows, string(r))
	}
	return
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "hudfont:", err)
	os.Exit(1)
}
